### ISSUE TITLE
Mozilla Github

### ISSUE THREAD

**Issue by halcance** [mozillabrasil/onboarding#1]
## Tarefas:
- [x] [Traduzir o documento](https://github.com/mozillabrasil/onboarding/blob/master/mozilla-github.md)
- [x] Mandar Pull request
- [x] Revisar
- [x] Postar no wiki

**Comment by maykonchagas** [comment]
@alipseight tem alguém já realizando tradução? posso assumir?

**Comment by halcance** [comment]
Pode sim @mchagas  obrigado pela contribuição!

**Comment by halcance** [comment]
Irei tentar traduzir o documento também para dar um suporte.

**Comment by jaimemaretoli** [comment]
Opa galera, vão notificando como anda a localização. Posso ajudar também. #GoMozilla!

**Comment by halcance** [comment]
Oi Jaime, infelizmente ainda não pude contribuir na tradução, caso queira começar fique à vontade para nos apresentar sua sugestão.

**Comment by maykonchagas** [comment]
Galera, vou trabalhar nisso hoje. Melhor ir fazendo PR de acordo com o que vai traduzindo, ou um final?

**Comment by maykonchagas** [comment]
Desconsiderem meu comentário acima sobre fazer PR. Fiz praticamente metade, visto que a grande parte do documento são links. Amanhã eu acabo tudo!

**Comment by maykonchagas** [comment]
@alipseight localização completa. Notei que não preciso mandar o PR, certo? Então já marquei tanto a task de tradução quanto de PR. Doc pronto pra revisão. Abraços!

**Comment by halcance** [comment]
Revisado e publicado, obrigado a todos.
