### ISSUE TITLE
Guia de Onboarding para WoMoz

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/onboarding#10]

**Comment by barrosgg** [comment]
Template: https://paper.dropbox.com/doc/Mozilla-Brasil-Onboarding-Layout-XxCAKqUyGqYThbIFtvHp9

**Comment by cyz** [comment]
@barrosgeraldo vou começar o rascunho do template de onboarding, acho necessário termos uma call com o time para definir o goal deste ano e direcionar as ações e projetos que serão desenvolvidos a partir desta call.

**Comment by barrosgg** [comment]
@cyz, você pode solicitar uma call no Discourse e no grupo do Telegram para começar essa movimentação?

**Comment by jaimemaretoli** [comment]
@cyz: pode se basear na [Wiki de L10n](https://wiki.mozilla.org/Brasil/L10n).

**Comment by barrosgg** [comment]
Atualização: Aberta chamada para reunião da WoMoz Brasil no Discourse.

**Comment by jaimemaretoli** [comment]
@barrosgeraldo @cyz temos algum andamento? Qual o status?

**Comment by jaimemaretoli** [comment]
Quem sabe linkamos com o site ou página da Wiki do WoMoz e encerramos essa issue? @barrosgeraldo @cyz o que acham?

**Comment by barrosgg** [comment]
@jaimemaretoli, nesse caso não resolve o problema, no site da WoMoz não há onboarding, o projeto está pendente de liderança e ninguém se manifestou.

@cyz @cynthiapereira, vamos marcar uma reunião para a próxima semana para falar sobre o futuro do WoMoz na comunidade?

**Comment by cyz** [comment]
Depois de algumas tentativas de reativação do time, optamos pela descontinuidade do programa no Brasil. O fechamento já foi comunicado nos canais da comunidade e no discourse: https://discourse.mozilla-community.org/t/its-time-to-moving/14040
