### ISSUE TITLE
Guia de Onboading para L10N

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/onboarding#11]

**Comment by barrosgg** [comment]
Template: https://paper.dropbox.com/doc/Mozilla-Brasil-Onboarding-Layout-XxCAKqUyGqYThbIFtvHp9

**Comment by maykonchagas** [comment]
O guia para L10n já foi criado. E foi posto para apreciação no grupo do Telegram do time [L10n pt-BR](https://telegram.me/mozillal10nptbr). Aos interessados, podem visualizar o documento no [Paper Dropbox](https://paper.dropbox.com/doc/Mozilla-Brasil-Localizao-L10n-Z8fqFX8TGnTn3TaKNeCdH#:uid=590359932232610&h2=L10n-%C3%A9-mais-do-que-simplesment) qualquer dúvida ou sugestão, podem comentar na própria edição, ou aqui na issue.

Abraços,

**Comment by maykonchagas** [comment]
@barrosgeraldo @jaimemaretoli esse layout já será postado direto na Wiki?, seria interessante deixar um modelo em MarkDown, o que acham?

**Comment by barrosgg** [comment]
@mchagas você pode adicionar a documentação de engajamento da L10N na pagina de L10N da Mozilla Brasil.

A documentação é clara, mas você acha que é interessante separar os projetos de localização por tópicos na sessão Começando? Exemplo:
- MDN
- Pontoon
- SUMO

Nesse caso, você pode adicionar um parágrafo para cada tópico e falar sobre o engajamento.

**Comment by maykonchagas** [comment]
Oi @barrosgeraldo, realizei a alteração pensando no que tu falou, veja se isso satisfaz. Como a ideia é ser breve, só aproveitei o que já estava escrito, separando em sessões como sugerido. Abraços,

**Comment by barrosgg** [comment]
@mchagas ficou ótimo, grande trabalho!
Assim que estiver na wiki será incrível para novos voluntários se engajarem.

**Comment by maykonchagas** [comment]
@barrosgeraldo já postei na [Wiki de L10n](https://wiki.mozilla.org/Brasil/L10n)
