### ISSUE TITLE
Guia de Onboarding para Mozilla Activate

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/onboarding#12]
Um resumo sobre a campanha e dicas para organizar atividades locais.

**Comment by barrosgg** [comment]
A onboarding para esta não é necessário tendo em vista que vamos trabalhar na tradução do site oficial.

**Comment by jaimemaretoli** [comment]
@barrosgeraldo: essa issue pode ser fechada? Se sim, já pode fechar. 😉

**Comment by barrosgg** [comment]
@mchagas, você sabe me dizer se o time de localização planeja localizar o site do Mozilla Activate?

**Comment by maykonchagas** [comment]
Opa! A situação do Mozilla Activate parece meio nebulosa pra mim. Houveram várias investidas, aparentemente começou com o @alipseight, depois houve uma revisão geral, que quem tocou (ou pelo menos as pessoas clonaram o repositório dele) foi o Guilhermo. Eu (re)trabalhei em cima do que o Magno havia feito e o meu [PR #126](https://github.com/mozilla/activate.mozilla.community/pull/126) está aguardando no repositório oficial da Mozilla.
Mas esse mesmo PR será integrado, ao menos foi solicitado, ao Pontoon, pois o Mozilla Activate está sendo migrado pra lá, como pode ser visto nessa issue [#34](https://github.com/mozilla/activate.mozilla.community/issues/34).

Ou seja, resumindo, nós precisamos aguardar.

**Comment by barrosgg** [comment]
@mchagas, muito obrigado pela resposta rápida aqui!

Eu vejo que houve atualizações há 10 dias atrás, vamos aguardar mais, assim que o PR for aprovado, nos avise aqui e vamos fechar esta.

**Comment by maykonchagas** [comment]
Certamente, assim que for atualizada, avisarei pra galera!

**Comment by halcance** [comment]
O PR do PT-BR já foi aceito, podemos fechar a issue?

**Comment by barrosgg** [comment]
@mchagas, você sabe me dizer se foi mesmo para o pontoon?

**Comment by cpswsg** [comment]
@barrosgeraldo foi para o pontoon, mas aconteceu algo e o mesmo foi retirado da produção.

**Comment by halcance** [comment]
Pelo que eu vi no issue tá no pontoon em fase de testes.

**Comment by barrosgg** [comment]
se foi ao pontoon, vamos reconhecer que a responsabilidade é do time de L10N, LOL. Close this, thank you.
