### ISSUE TITLE
Reescrever uma nova pagina na Wiki para Onboarding

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/onboarding#14]
- [x] Descrição da onboarding team
- [x] SOPs
- [x] Recursos
- [x] Ações (feitas, a serem feitas e status)
- [x] Discussões
- [x] Facilitadores

**Comment by barrosgg** [comment]
Nova proposta da wiki: https://wiki.mozilla.org/Brasil/Onboarding/rewrite.

Atribuindo este a @jaimemaretoli para revisão e aprovação final aqui.

**Comment by jaimemaretoli** [comment]
@barrosgeraldo revisado e aprovado!

**Comment by barrosgg** [comment]
Movida para a página principal da Onboarding: https://wiki.mozilla.org/Brasil/Onboarding/
