### ISSUE TITLE
Escrever e documentar um Procedimento Operacional Padrão para o Onboarding

### ISSUE THREAD

**Issue by jaimemaretoli** [mozillabrasil/onboarding#6]
O time de Onboarding realizará o levantamento do voluntário, como Nome, Faixa etária, Trabalha/estuda, Cidade, Tempo disponível para contribuição, área de interesse para contribuição, se já contribuiu com software livre e mais;

**Comment by jaimemaretoli** [comment]
Vamos descrever como é possível fazer o onboarding agora:

- Um possível voluntário chega na Wiki, no website da Mozilla, nas redes sociais ou em eventos e atividades presenciais;
- O voluntário é encaminhado para a pagina Participe da Mozilla Brasil, onde ele tem acesso a todos os projetos atuais que são suportados ou não pela comunidade;
- O voluntário escolhe um projeto para se engajar e clica em um link para uma documentação sobre como se engajar naquele time/projeto.

**Comment by jaimemaretoli** [comment]
Os times agora precisam criar uma simples documentação informando como o voluntário pode se engajar no seu time e projeto. 

Baseado no Community Playbook, nós já temos um conjunto de informações necessárias, existe um [layout](https://paper.dropbox.com/doc/Mozilla-Brasil-Onboarding-Layout-XxCAKqUyGqYThbIFtvHp9), os times podem copiar e criar seus próprios, fazendo as modificações necessárias, após criar e definir isto como aprovado pelo time, adicionar a uma pagina na wiki relacionado ao projeto.

**Comment by jaimemaretoli** [comment]
- [ ] Atualizar o website da Mozilla Brasil, há novos projetos e outros precisam de uma descrição melhor.
- [ ] Receber feedback aqui sobre o processo de onboarding e como pode ser melhorado, além de apresentar a comunidade em uma chamada/reunião o processo atual de onboarding, e se mostrar aberto para sugestões.

**Comment by jaimemaretoli** [comment]
A documentação sobre Mozilla Clubs está pronta: https://wiki.mozilla.org/Brasil/Mozilla_Leadership_Network/Mozilla_Clubs

https://discourse.mozilla-community.org/t/inicio-da-definicao-processo-de-onboarding-da-comunidade-mozilla-brasil/9937/48?u=jaimemaretoli

**Comment by barrosgg** [comment]
@jaimemaretoli, como você acha que podemos apresentar esse processo? Uma ilustração? Ou apenas pontuando o passo a passo?

Acredito que após as nossas tarefas estarem prontas, nós podemos criar uma apresentação de slides e um bate papo com a liderança de todos os times para discutir a onboarding.

**Comment by jaimemaretoli** [comment]
@barrosgeraldo, seria muito legal uma ilustração, ou mesmo, algo mais interativo. Mas acho que um passo a passo com links e mais na nossa Wiki já servirá pra galera. Sobre os slides, acho muito válido a gente conversar com os times funcionais sobre.

**Comment by barrosgg** [comment]
Isso, assim que tivermos algo, marcamos uma reunião com facilitadores de todos os times para receber feedback e novas ideias, pois os times vão poder fornecer mais detalhes se esta onboarding funciona ou não, e o que precisamos melhorar.

Talvez  uma ilustração simples com Google Slides ou Canva são interessantes para mostrar o funcionamento da onboarding, de modo geral.

É importante criar links curtos e fáceis para as documentações específicas de cada time, isso ajuda a trabalhar com marketing, engajamento direto em um treinamento presencial, redes sociais etc.
Exemplo, no caso do Mozilla Campus Clubs, podemos criar um link curto mzl.la/mccbr.

O que acha?

**Comment by jaimemaretoli** [comment]
Entendido @barrosgeraldo. Gostei do Canvas, acho que pode ser muito útil sempre que precisarmos explicar o Onboarding.

Eu sempre quis saber como criar esses links, mas alguma vez vi que deve-se ter um determinado tipo de acesso — posso estar enganado — para conseguir criar esses links curtos. Acho ótimo isso tudo! 😃

**Comment by barrosgg** [comment]
Os sites da Mozilla são encurtados pelo https://bitly.com

**Comment by barrosgg** [comment]
@jaimemaretoli, já temos algo pronto para esta tarefa?

**Comment by barrosgg** [comment]
Escrito na Wiki.
