### ISSUE TITLE
Obter voluntários dos times funcionais no Onboarding para facilitar o processo

### ISSUE THREAD

**Issue by jaimemaretoli** [mozillabrasil/onboarding#7]
Pessoas do time de onboarding devem participar de times funcionais e pessoas dos times funcionais devem passar informações destes times para pessoas do time de onboarding;

**Comment by barrosgg** [comment]
Os próprios líderes quando preenchem o [template](https://paper.dropbox.com/doc/Mozilla-Brasil-Onboarding-Layout-XxCAKqUyGqYThbIFtvHp9) já indicam quem serão os facilitadores, uma vez que os times foram orientados a organizarem a onboarding, documentar e definir seus próprios processos.

**Comment by cyz** [comment]
@barrosgeraldo @jaimemaretoli desculpem a demora em conectar na task, onde devo submeter uma base geral do womoz?

**Comment by jaimemaretoli** [comment]
@cyz com uma página na Wiki mesmo. Pode se basear no [tamplate criado pelo @barrosgeraldo](https://paper.dropbox.com/doc/Mozilla-Brasil-Onboarding-Layout-XxCAKqUyGqYThbIFtvHp9) e também no de [L10n](https://wiki.mozilla.org/Brasil/L10n) — caso ainda não exista uma página para o WoMoz. Todas as páginas dos times funcionais serão linkados na [página principal do Onboarding](https://wiki.mozilla.org/Brasil/Onboarding/). 😉
