### ISSUE TITLE
Guia de Onboarding para Mozilla Support

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/onboarding#8]

**Comment by barrosgg** [comment]
Eu não consigo encontrar o Thiago e Jhonatas para marcar aqui.

**Comment by barrosgg** [comment]
Template: https://paper.dropbox.com/doc/Mozilla-Brasil-Onboarding-Layout-XxCAKqUyGqYThbIFtvHp9

**Comment by cpswsg** [comment]
@barrosgeraldo O SUMO terá seu próprio canal para onboarding, que entrará definitivamente no ar em meados de Janeiro de 2017.

cc: @thiagopolicena e @jhonatasrm

**Comment by barrosgg** [comment]
Perfeito.

**Comment by jaimemaretoli** [comment]
@cynthiapereira como está o canal de onboarding do SUMO?

**Comment by barrosgg** [comment]
@jaimemaretoli, vou manter esta issue aberta, assim não vamos esquecer de atualizar o site com relação ao novo canal para onboarding do SUMO.

**Comment by jaimemaretoli** [comment]
@barrosgeraldo @cynthiapereira: sabem qual o status?

**Comment by cpswsg** [comment]
@jaimemaretoli O canal de onboarding do SUMO funciona por meio do telegram do grupo e do site https://sumobr.org.
